services:
    ezpublish.console.command.regenerate_url_aliases:
        class: eZ\Bundle\EzPublishCoreBundle\Command\RegenerateUrlAliasesCommand
        arguments:
            # intentionally passing inner repository to avoid sending Signals due to performance issues
            - '@ezpublish.api.inner_repository'
            - '@?logger'
        tags:
            - { name: console.command }

    ezpublish.console.command.import_password_blaclist:
        class: eZ\Bundle\EzPublishCoreBundle\Command\ImportPasswordBlacklistCommand
        arguments:
            - '@ezpublish.spi.persistence.legacy.transactionhandler'
            - '@ezpublish.spi.persistence.legacy.password_blacklist.handler'
        tags:
            - { name: console.command }
